name: Upload website + configurator (VDX FTP, zonder build)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Upload 1: root-site naar /httpdocs/
      - name: Upload root site (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /httpdocs/
          local-dir: ./
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/dist/**
            **/.DS_Store
            **/Thumbs.db
            **/*.md

      # Upload 2: de volledige configurator-map naar /httpdocs/configurator/
      - name: Upload configurator build (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /httpdocs/configurator/
          local-dir: ./dist/assets/
          exclude: |
            **/.DS_Store
            **/Thumbs.db
