name: Upload website + configurator (VDX FTP, zonder build)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Root site naar /httpdocs (zoals je al had)
      - name: Upload root site (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /httpdocs/
          local-dir: ./
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/dist/**        # <-- we uploaden dist apart hieronder
            **/.DS_Store
            **/Thumbs.db
            **/*.md

      # 2) ALLEEN het configurator index.html naar /httpdocs/configurator/
      - name: Upload configurator index.html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /httpdocs/configurator/
          local-dir: ./dist/assets/
          exclude: |
            **/*.js
            **/*.css
            **/*.map
            **/*.png
            **/*.jpg
            **/*.jpeg
            **/*.gif
            **/*.svg

      # 3) ALLE assets (js/css/img) naar /httpdocs/assets/
      - name: Upload configurator assets
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /httpdocs/assets/
          local-dir: ./dist/assets/
          exclude: |
            index.html       # geen index hier; die ging naar /configurator/
