name: Upload website via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: ${{ secrets.FTP_DIR }}
          local-dir: .
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
            **/*.md
